---
- name: Create a Network
  gcp_compute_network:
    state: present
    name: iwcs-img-ppd
    auto_create_subnetworks: true
    service_account_file: "{{ gcp_credentials_file }}"
    project: "{{ gcp_project_name }}"
    auth_kind: serviceaccount
  register: network

- name: Create a Subnetwork
  gcp_compute_subnetwork:
    auth_kind: serviceaccount
    name: internal-access-us-east4
    service_account_file: "{{ gcp_credentials_file }}"
    network: "{{ network }}"
    ip_cidr_range: 10.238.4.128/25
    region: "{{ gcp_region }}"
    project: "{{ gcp_project_name }}"
  register: subnetwork
